language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: NeWGpX4mPJRxv0cyT0G3S9vxCyuOBLAP/Yzi8GTLWXkC54cKwMgbXlJZJ5XbzfKGdZuRnUsOswpAwM3vWtJypxZpFrHiGi473jGeNTleKzg//KGVRu1rfHe7z/jnloJlZQ9tGFl3tJqL7LsqYUmZGLlhZVndTVR2mcZ7a/U6Gfo=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: GRH2EgxcxM/LEOEeBnofllzXoHTttN0ZN4dSEdH5g18XA6efcFuGRmaUXbzViTB+U9e0e+3O2t2rKRyrlYsDgni9Mm/Za6+JOaoiGxhSwAFDiPwUKXQCgUrskhRxEMJdTwtp6bTRfkJGNUt0DTWdp2xFq3JLIs69m+lIyWwDqXY=
sudo: false
